### ISSUE TITLE
Bug in SBL signups page

### ISSUE THREAD

**Issue by lauriconeves** [raphleu/arma-rankings#19]
1. Navigate to https://armarankings.com/rankings?match_subtype_id=sbl-s2
2. In the count down timer for next game click on "SBL signups..." link
3. The page is throwing a 500 "Internal Server error"

<img width="1673" alt="Screen Shot 2020-12-19 at 12 10 27 PM" src="https://user-images.githubusercontent.com/12365531/102695200-c7361200-41f3-11eb-9f25-76d1ff0b7aa6.png">

**Comment by raphleu** [comment]
Fixed :) Thanks Lau
